title: PhoenixMC
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://cstate.mnts.lt'
params:
  disableDarkMode: true
  shortDateFormat: '15:04 — Jan 2'
  down: '#e60000'
  systems:
    - category: Servers
      name: Bungeecord
    - category: Servers
      name: Hub
    - category: Servers
      name: Survival
    - name: Factions
      category: Servers
  dateFormat: 'January 2, 2006 at 3:04 PM'
  brand: '#0a0c0f'
  headerTextColor: white
  logo: /logo.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: '#cc4400'
  notice: '#24478f'
  incidentHistoryFormat: none
  ok: '#008000'
  categories:
    - closed: true
      untited: false
      name: Servers
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  useLargeHeaderDesign: false
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
